### ISSUE TITLE
查看集群状态只显示当前服务器节点的mq状态，不能显示全部

### ISSUE THREAD

**Issue by post707** [tianctrl/rabbitmq-cluster-helm#1]
[root@k8smaster examples]# FIRST_POD=$(kubectl get pods --namespace test-rabbitmq -l 'app=rabbitmq' -o jsonpath='{.items[0].metadata.name }')
[root@k8smaster examples]# kubectl exec --namespace=test-rabbitmq $FIRST_POD rabbitmqctl cluster_status
Cluster status of node 'rabbit@12.240.3.153'
[{nodes,[{disc,['rabbit@12.240.3.153']}]},
 {running_nodes,['rabbit@12.240.3.153']},
 {cluster_name,<<"rabbit@rabbitmq-0.rabbitmq.test-rabbitmq.svc.cluster.local">>},
 {partitions,[]},
 {alarms,[{'rabbit@12.240.3.153',[]}]}]

以上未执行查看集群状态命令的结果，为什么不显示所有的mq状态呢？哪里部署有问题啊？

**Comment by tianctrl** [comment]
@post707 我自己部署的时候,遇到这个问题, 一个是service account不对造成的; 另一个是网络问题造成的, 换了个集群就好了. 你可以查看一下每个pod的log.

**Comment by post707** [comment]
@tianctrl 谢谢
