### ISSUE TITLE
集群状态不对

### ISSUE THREAD

**Issue by post707** [tianctrl/rabbitmq-cluster-helm#2]
rabbitmqctl cluster_status
Cluster status of node 'rabbit@12.240.4.70' ...
[{nodes,[{disc,['rabbit@12.240.4.70']}]},
 {running_nodes,['rabbit@12.240.4.70']},
 {cluster_name,<<"rabbit@rabbitmq-cluster-rabbitmq-cluster-2.rabbitmq-cluster-rabbitmq-cluster.rabbitmq-cluster.svc.cluster.local">>},
 {partitions,[]},
 {alarms,[{'rabbit@12.240.4.70',[]}]}]

**Comment by tianctrl** [comment]
请参考[ issue1](https://github.com/tianctrl/rabbitmq-cluster-helm/issues/1)

**Comment by post707** [comment]
@tianctrl  不好意思，之前也是我问的，忘了，~已经解决了。
另外请教一下，这个配置默认有没有持久化，pod重启后数据会不会有丢失？

**Comment by tianctrl** [comment]
默认没有持久化的，因为是一个示例，就没做很深入。
